# SITE CONFIGURATION
title: Refreshing Waters # your site title
author:  # You :P
description: > # Meta description of Homepage
  Refreshing Waters. The Christian Ministry dedicated to the rejuvination of those who further God's mission.
baseurl: "refreshingwaters" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Jeremy Bourne
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Donate', link: '/donate'}
tagline: >
  Serving Christ through Rejuvination

hero_img: https://live.staticflickr.com/65535/48524038596_f00c48a733_b.jpg # Main background image

email: jjbourne712@gmail.com # email for form submission

twitter_username: fake_twitter # replace with your_twitter_username or comment to remove link from footer
github_username:   # replace with your_github_username or comment to remove link from footer
instagram_username: fake_instagram # replace with your_instagram_username or comment to remove link from footer

#disqus:
 # shortname: jjbou # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
